# ---------------------------------------------------------------------------
# Real OTP delivery for CAM FIX (SMS + Gmail email).
#
# The OTP codes are ALWAYS generated by this Spring backend. This script only
# turns on real *delivery* by filling in provider credentials. Without it the
# codes are just written to the server log (and returned as `devCode` while
# app.otp.expose-code=true).
#
# HOW TO USE
#   1. Copy this file to  run-with-otp-delivery.ps1  (keep that name off
#      version control - it will hold secrets).
#   2. Fill in ONE of the SMS options below (+ email if you want it).
#   3. From C:\Cam\Backend run:   . .\run-with-otp-delivery.ps1
#      (the leading "dot space" matters - it sets the vars in your shell,
#       then starts the API.)
# ---------------------------------------------------------------------------

# ==== SMS - pick ONE ======================================================

# ---- Option A: TextBelt (no signup) ------------------------------------
# Easiest way to get a real text. 'textbelt' = free tier, 1 SMS/day per
# server IP. For volume, buy a key at https://textbelt.com (then paste it
# here). Works with international numbers, including +855.
$env:TEXTBELT_KEY = "textbelt"

# ---- Option B: Twilio (account required) -----------------------------
# Create a free trial at https://www.twilio.com/try-twilio
#   Console home  -> Account SID  and  Auth Token
#   Phone Numbers -> get a trial number  (TWILIO_FROM_NUMBER)
#   Trial limit: can only text numbers verified under "Verified Caller IDs".
# If these three are set they take priority over TEXTBELT_KEY.
# $env:TWILIO_ACCOUNT_SID = "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# $env:TWILIO_AUTH_TOKEN  = "your_auth_token_here"
# $env:TWILIO_FROM_NUMBER = "+1XXXXXXXXXX"

# ==== Email OTP, via Gmail SMTP (optional) ================================
# On the Google account you want to send from:
#   1. Turn on 2-Step Verification (https://myaccount.google.com/security)
#   2. Create an App Password (https://myaccount.google.com/apppasswords)
#      -> 16 characters, no spaces. Your normal Gmail password will NOT work.
# $env:MAIL_HOST     = "smtp.gmail.com"
# $env:MAIL_PORT     = "587"
# $env:MAIL_USERNAME = "you@gmail.com"
# $env:MAIL_PASSWORD = "abcdefghijklmnop"          # the 16-char App Password
# $env:MAIL_FROM     = "CAM FIX <you@gmail.com>"

# ==== Stop echoing the code in the API response once delivery works ======
# $env:APP_OTP_EXPOSE_CODE = "false"

# -------------------------------------------------------------------------
Write-Host "Starting CAM FIX API with real OTP delivery..." -ForegroundColor Cyan
& "$PSScriptRoot\mvnw.cmd" spring-boot:run
